"""add_dashboard_tables

Revision ID: b9f3949fc2ac
Revises: 0140674b6e0b
Create Date: 2026-03-22 21:29:35.071559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9f3949fc2ac'
down_revision: Union[str, Sequence[str], None] = '0140674b6e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mistake_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('example_from_transcript', sa.Text(), nullable=False),
    sa.Column('correction', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mistake_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mistake_patterns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistake_patterns_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mistake_patterns_user_id'), ['user_id'], unique=False)

    op.create_table('vocabulary_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('word_or_phrase', sa.String(length=200), nullable=False),
    sa.Column('hebrew_translation', sa.String(length=200), nullable=False),
    sa.Column('source_context', sa.Text(), nullable=False),
    sa.Column('mastery_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_items_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    with op.batch_alter_table('vocabulary_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_session_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_items_id'))

    op.drop_table('vocabulary_items')
    with op.batch_alter_table('mistake_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mistake_patterns_user_id'))
        batch_op.drop_index(batch_op.f('ix_mistake_patterns_session_id'))
        batch_op.drop_index(batch_op.f('ix_mistake_patterns_id'))

    op.drop_table('mistake_patterns')
    # ### end Alembic commands ###
